/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as InviteInvitationIdRouteImport } from './routes/invite/$invitationId'
import { Route as DashboardVehiclesRouteImport } from './routes/dashboard/vehicles'
import { Route as DashboardVacationsRouteImport } from './routes/dashboard/vacations'
import { Route as DashboardToursRouteImport } from './routes/dashboard/tours'
import { Route as DashboardTemplatesRouteImport } from './routes/dashboard/templates'
import { Route as DashboardSchedulesRouteImport } from './routes/dashboard/schedules'
import { Route as DashboardDriversRouteImport } from './routes/dashboard/drivers'
import { Route as DashboardCustomersRouteImport } from './routes/dashboard/customers'
import { Route as DashboardBookingsRouteImport } from './routes/dashboard/bookings'
import { Route as DashboardAssignmentsRouteImport } from './routes/dashboard/assignments'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const InviteInvitationIdRoute = InviteInvitationIdRouteImport.update({
  id: '/invite/$invitationId',
  path: '/invite/$invitationId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardVehiclesRoute = DashboardVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVacationsRoute = DashboardVacationsRouteImport.update({
  id: '/vacations',
  path: '/vacations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardToursRoute = DashboardToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTemplatesRoute = DashboardTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSchedulesRoute = DashboardSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDriversRoute = DashboardDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCustomersRoute = DashboardCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBookingsRoute = DashboardBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAssignmentsRoute = DashboardAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/assignments': typeof DashboardAssignmentsRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/drivers': typeof DashboardDriversRoute
  '/dashboard/schedules': typeof DashboardSchedulesRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/dashboard/tours': typeof DashboardToursRoute
  '/dashboard/vacations': typeof DashboardVacationsRoute
  '/dashboard/vehicles': typeof DashboardVehiclesRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/assignments': typeof DashboardAssignmentsRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/drivers': typeof DashboardDriversRoute
  '/dashboard/schedules': typeof DashboardSchedulesRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/dashboard/tours': typeof DashboardToursRoute
  '/dashboard/vacations': typeof DashboardVacationsRoute
  '/dashboard/vehicles': typeof DashboardVehiclesRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/assignments': typeof DashboardAssignmentsRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/drivers': typeof DashboardDriversRoute
  '/dashboard/schedules': typeof DashboardSchedulesRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/dashboard/tours': typeof DashboardToursRoute
  '/dashboard/vacations': typeof DashboardVacationsRoute
  '/dashboard/vehicles': typeof DashboardVehiclesRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/analytics'
    | '/dashboard/assignments'
    | '/dashboard/bookings'
    | '/dashboard/customers'
    | '/dashboard/drivers'
    | '/dashboard/schedules'
    | '/dashboard/templates'
    | '/dashboard/tours'
    | '/dashboard/vacations'
    | '/dashboard/vehicles'
    | '/invite/$invitationId'
    | '/dashboard/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/analytics'
    | '/dashboard/assignments'
    | '/dashboard/bookings'
    | '/dashboard/customers'
    | '/dashboard/drivers'
    | '/dashboard/schedules'
    | '/dashboard/templates'
    | '/dashboard/tours'
    | '/dashboard/vacations'
    | '/dashboard/vehicles'
    | '/invite/$invitationId'
    | '/dashboard'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/analytics'
    | '/dashboard/assignments'
    | '/dashboard/bookings'
    | '/dashboard/customers'
    | '/dashboard/drivers'
    | '/dashboard/schedules'
    | '/dashboard/templates'
    | '/dashboard/tours'
    | '/dashboard/vacations'
    | '/dashboard/vehicles'
    | '/invite/$invitationId'
    | '/dashboard/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  InviteInvitationIdRoute: typeof InviteInvitationIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/invite/$invitationId': {
      id: '/invite/$invitationId'
      path: '/invite/$invitationId'
      fullPath: '/invite/$invitationId'
      preLoaderRoute: typeof InviteInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/vehicles': {
      id: '/dashboard/vehicles'
      path: '/vehicles'
      fullPath: '/dashboard/vehicles'
      preLoaderRoute: typeof DashboardVehiclesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/vacations': {
      id: '/dashboard/vacations'
      path: '/vacations'
      fullPath: '/dashboard/vacations'
      preLoaderRoute: typeof DashboardVacationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tours': {
      id: '/dashboard/tours'
      path: '/tours'
      fullPath: '/dashboard/tours'
      preLoaderRoute: typeof DashboardToursRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/templates': {
      id: '/dashboard/templates'
      path: '/templates'
      fullPath: '/dashboard/templates'
      preLoaderRoute: typeof DashboardTemplatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/schedules': {
      id: '/dashboard/schedules'
      path: '/schedules'
      fullPath: '/dashboard/schedules'
      preLoaderRoute: typeof DashboardSchedulesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/drivers': {
      id: '/dashboard/drivers'
      path: '/drivers'
      fullPath: '/dashboard/drivers'
      preLoaderRoute: typeof DashboardDriversRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/customers': {
      id: '/dashboard/customers'
      path: '/customers'
      fullPath: '/dashboard/customers'
      preLoaderRoute: typeof DashboardCustomersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bookings': {
      id: '/dashboard/bookings'
      path: '/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof DashboardBookingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/assignments': {
      id: '/dashboard/assignments'
      path: '/assignments'
      fullPath: '/dashboard/assignments'
      preLoaderRoute: typeof DashboardAssignmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardAssignmentsRoute: typeof DashboardAssignmentsRoute
  DashboardBookingsRoute: typeof DashboardBookingsRoute
  DashboardCustomersRoute: typeof DashboardCustomersRoute
  DashboardDriversRoute: typeof DashboardDriversRoute
  DashboardSchedulesRoute: typeof DashboardSchedulesRoute
  DashboardTemplatesRoute: typeof DashboardTemplatesRoute
  DashboardToursRoute: typeof DashboardToursRoute
  DashboardVacationsRoute: typeof DashboardVacationsRoute
  DashboardVehiclesRoute: typeof DashboardVehiclesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardAssignmentsRoute: DashboardAssignmentsRoute,
  DashboardBookingsRoute: DashboardBookingsRoute,
  DashboardCustomersRoute: DashboardCustomersRoute,
  DashboardDriversRoute: DashboardDriversRoute,
  DashboardSchedulesRoute: DashboardSchedulesRoute,
  DashboardTemplatesRoute: DashboardTemplatesRoute,
  DashboardToursRoute: DashboardToursRoute,
  DashboardVacationsRoute: DashboardVacationsRoute,
  DashboardVehiclesRoute: DashboardVehiclesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  InviteInvitationIdRoute: InviteInvitationIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
