/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as InviteInvitationIdRouteImport } from './routes/invite/$invitationId'
import { Route as DashboardVehiclesRouteImport } from './routes/dashboard/vehicles'
import { Route as DashboardVacationsRouteImport } from './routes/dashboard/vacations'
import { Route as DashboardToursRouteImport } from './routes/dashboard/tours'
import { Route as DashboardTemplatesRouteImport } from './routes/dashboard/templates'
import { Route as DashboardSchedulesRouteImport } from './routes/dashboard/schedules'
import { Route as DashboardOtaRouteImport } from './routes/dashboard/ota'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard/notifications'
import { Route as DashboardDriversRouteImport } from './routes/dashboard/drivers'
import { Route as DashboardCustomersRouteImport } from './routes/dashboard/customers'
import { Route as DashboardCategoriesRouteImport } from './routes/dashboard/categories'
import { Route as DashboardBookingsRouteImport } from './routes/dashboard/bookings'
import { Route as DashboardAssignmentsRouteImport } from './routes/dashboard/assignments'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as BookSlugRouteImport } from './routes/book/$slug'
import { Route as DashboardVehiclesNewRouteImport } from './routes/dashboard/vehicles/new'
import { Route as DashboardVehiclesVehicleIdRouteImport } from './routes/dashboard/vehicles/$vehicleId'
import { Route as DashboardVacationsNewRouteImport } from './routes/dashboard/vacations/new'
import { Route as DashboardVacationsVacationIdRouteImport } from './routes/dashboard/vacations/$vacationId'
import { Route as DashboardToursNewRouteImport } from './routes/dashboard/tours/new'
import { Route as DashboardToursTourIdRouteImport } from './routes/dashboard/tours/$tourId'
import { Route as DashboardTemplatesNewRouteImport } from './routes/dashboard/templates/new'
import { Route as DashboardTemplatesTemplateIdRouteImport } from './routes/dashboard/templates/$templateId'
import { Route as DashboardSettingsPaymentsRouteImport } from './routes/dashboard/settings/payments'
import { Route as DashboardSchedulesNewRouteImport } from './routes/dashboard/schedules/new'
import { Route as DashboardSchedulesScheduleIdRouteImport } from './routes/dashboard/schedules/$scheduleId'
import { Route as DashboardNotificationsSettingsRouteImport } from './routes/dashboard/notifications/settings'
import { Route as DashboardNotificationsNewRouteImport } from './routes/dashboard/notifications/new'
import { Route as DashboardNotificationsTemplateIdRouteImport } from './routes/dashboard/notifications/$templateId'
import { Route as DashboardDriversNewRouteImport } from './routes/dashboard/drivers/new'
import { Route as DashboardDriversDriverIdRouteImport } from './routes/dashboard/drivers/$driverId'
import { Route as DashboardCustomersNewRouteImport } from './routes/dashboard/customers/new'
import { Route as DashboardCustomersCustomerIdRouteImport } from './routes/dashboard/customers/$customerId'
import { Route as DashboardBookingsNewRouteImport } from './routes/dashboard/bookings/new'
import { Route as DashboardBookingsBookingIdRouteImport } from './routes/dashboard/bookings/$bookingId'
import { Route as DashboardAssignmentsNewRouteImport } from './routes/dashboard/assignments/new'
import { Route as DashboardAssignmentsAssignmentIdRouteImport } from './routes/dashboard/assignments/$assignmentId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardToursTourIdEditRouteImport } from './routes/dashboard/tours/$tourId/edit'
import { Route as DashboardCustomersCustomerIdEditRouteImport } from './routes/dashboard/customers/$customerId/edit'
import { Route as DashboardBookingsBookingIdEditRouteImport } from './routes/dashboard/bookings/$bookingId/edit'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const InviteInvitationIdRoute = InviteInvitationIdRouteImport.update({
  id: '/invite/$invitationId',
  path: '/invite/$invitationId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardVehiclesRoute = DashboardVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVacationsRoute = DashboardVacationsRouteImport.update({
  id: '/vacations',
  path: '/vacations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardToursRoute = DashboardToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTemplatesRoute = DashboardTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSchedulesRoute = DashboardSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOtaRoute = DashboardOtaRouteImport.update({
  id: '/ota',
  path: '/ota',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDriversRoute = DashboardDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCustomersRoute = DashboardCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCategoriesRoute = DashboardCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBookingsRoute = DashboardBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAssignmentsRoute = DashboardAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardVehiclesNewRoute = DashboardVehiclesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardVehiclesRoute,
} as any)
const DashboardVehiclesVehicleIdRoute =
  DashboardVehiclesVehicleIdRouteImport.update({
    id: '/$vehicleId',
    path: '/$vehicleId',
    getParentRoute: () => DashboardVehiclesRoute,
  } as any)
const DashboardVacationsNewRoute = DashboardVacationsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardVacationsRoute,
} as any)
const DashboardVacationsVacationIdRoute =
  DashboardVacationsVacationIdRouteImport.update({
    id: '/$vacationId',
    path: '/$vacationId',
    getParentRoute: () => DashboardVacationsRoute,
  } as any)
const DashboardToursNewRoute = DashboardToursNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardToursRoute,
} as any)
const DashboardToursTourIdRoute = DashboardToursTourIdRouteImport.update({
  id: '/$tourId',
  path: '/$tourId',
  getParentRoute: () => DashboardToursRoute,
} as any)
const DashboardTemplatesNewRoute = DashboardTemplatesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardTemplatesRoute,
} as any)
const DashboardTemplatesTemplateIdRoute =
  DashboardTemplatesTemplateIdRouteImport.update({
    id: '/$templateId',
    path: '/$templateId',
    getParentRoute: () => DashboardTemplatesRoute,
  } as any)
const DashboardSettingsPaymentsRoute =
  DashboardSettingsPaymentsRouteImport.update({
    id: '/settings/payments',
    path: '/settings/payments',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSchedulesNewRoute = DashboardSchedulesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardSchedulesRoute,
} as any)
const DashboardSchedulesScheduleIdRoute =
  DashboardSchedulesScheduleIdRouteImport.update({
    id: '/$scheduleId',
    path: '/$scheduleId',
    getParentRoute: () => DashboardSchedulesRoute,
  } as any)
const DashboardNotificationsSettingsRoute =
  DashboardNotificationsSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardNotificationsRoute,
  } as any)
const DashboardNotificationsNewRoute =
  DashboardNotificationsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => DashboardNotificationsRoute,
  } as any)
const DashboardNotificationsTemplateIdRoute =
  DashboardNotificationsTemplateIdRouteImport.update({
    id: '/$templateId',
    path: '/$templateId',
    getParentRoute: () => DashboardNotificationsRoute,
  } as any)
const DashboardDriversNewRoute = DashboardDriversNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardDriversRoute,
} as any)
const DashboardDriversDriverIdRoute =
  DashboardDriversDriverIdRouteImport.update({
    id: '/$driverId',
    path: '/$driverId',
    getParentRoute: () => DashboardDriversRoute,
  } as any)
const DashboardCustomersNewRoute = DashboardCustomersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardCustomersRoute,
} as any)
const DashboardCustomersCustomerIdRoute =
  DashboardCustomersCustomerIdRouteImport.update({
    id: '/$customerId',
    path: '/$customerId',
    getParentRoute: () => DashboardCustomersRoute,
  } as any)
const DashboardBookingsNewRoute = DashboardBookingsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardBookingsRoute,
} as any)
const DashboardBookingsBookingIdRoute =
  DashboardBookingsBookingIdRouteImport.update({
    id: '/$bookingId',
    path: '/$bookingId',
    getParentRoute: () => DashboardBookingsRoute,
  } as any)
const DashboardAssignmentsNewRoute = DashboardAssignmentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardAssignmentsRoute,
} as any)
const DashboardAssignmentsAssignmentIdRoute =
  DashboardAssignmentsAssignmentIdRouteImport.update({
    id: '/$assignmentId',
    path: '/$assignmentId',
    getParentRoute: () => DashboardAssignmentsRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardToursTourIdEditRoute =
  DashboardToursTourIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => DashboardToursTourIdRoute,
  } as any)
const DashboardCustomersCustomerIdEditRoute =
  DashboardCustomersCustomerIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => DashboardCustomersCustomerIdRoute,
  } as any)
const DashboardBookingsBookingIdEditRoute =
  DashboardBookingsBookingIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => DashboardBookingsBookingIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/book/$slug': typeof BookSlugRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/assignments': typeof DashboardAssignmentsRouteWithChildren
  '/dashboard/bookings': typeof DashboardBookingsRouteWithChildren
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/customers': typeof DashboardCustomersRouteWithChildren
  '/dashboard/drivers': typeof DashboardDriversRouteWithChildren
  '/dashboard/notifications': typeof DashboardNotificationsRouteWithChildren
  '/dashboard/ota': typeof DashboardOtaRoute
  '/dashboard/schedules': typeof DashboardSchedulesRouteWithChildren
  '/dashboard/templates': typeof DashboardTemplatesRouteWithChildren
  '/dashboard/tours': typeof DashboardToursRouteWithChildren
  '/dashboard/vacations': typeof DashboardVacationsRouteWithChildren
  '/dashboard/vehicles': typeof DashboardVehiclesRouteWithChildren
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/assignments/$assignmentId': typeof DashboardAssignmentsAssignmentIdRoute
  '/dashboard/assignments/new': typeof DashboardAssignmentsNewRoute
  '/dashboard/bookings/$bookingId': typeof DashboardBookingsBookingIdRouteWithChildren
  '/dashboard/bookings/new': typeof DashboardBookingsNewRoute
  '/dashboard/customers/$customerId': typeof DashboardCustomersCustomerIdRouteWithChildren
  '/dashboard/customers/new': typeof DashboardCustomersNewRoute
  '/dashboard/drivers/$driverId': typeof DashboardDriversDriverIdRoute
  '/dashboard/drivers/new': typeof DashboardDriversNewRoute
  '/dashboard/notifications/$templateId': typeof DashboardNotificationsTemplateIdRoute
  '/dashboard/notifications/new': typeof DashboardNotificationsNewRoute
  '/dashboard/notifications/settings': typeof DashboardNotificationsSettingsRoute
  '/dashboard/schedules/$scheduleId': typeof DashboardSchedulesScheduleIdRoute
  '/dashboard/schedules/new': typeof DashboardSchedulesNewRoute
  '/dashboard/settings/payments': typeof DashboardSettingsPaymentsRoute
  '/dashboard/templates/$templateId': typeof DashboardTemplatesTemplateIdRoute
  '/dashboard/templates/new': typeof DashboardTemplatesNewRoute
  '/dashboard/tours/$tourId': typeof DashboardToursTourIdRouteWithChildren
  '/dashboard/tours/new': typeof DashboardToursNewRoute
  '/dashboard/vacations/$vacationId': typeof DashboardVacationsVacationIdRoute
  '/dashboard/vacations/new': typeof DashboardVacationsNewRoute
  '/dashboard/vehicles/$vehicleId': typeof DashboardVehiclesVehicleIdRoute
  '/dashboard/vehicles/new': typeof DashboardVehiclesNewRoute
  '/dashboard/bookings/$bookingId/edit': typeof DashboardBookingsBookingIdEditRoute
  '/dashboard/customers/$customerId/edit': typeof DashboardCustomersCustomerIdEditRoute
  '/dashboard/tours/$tourId/edit': typeof DashboardToursTourIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/book/$slug': typeof BookSlugRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/assignments': typeof DashboardAssignmentsRouteWithChildren
  '/dashboard/bookings': typeof DashboardBookingsRouteWithChildren
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/customers': typeof DashboardCustomersRouteWithChildren
  '/dashboard/drivers': typeof DashboardDriversRouteWithChildren
  '/dashboard/notifications': typeof DashboardNotificationsRouteWithChildren
  '/dashboard/ota': typeof DashboardOtaRoute
  '/dashboard/schedules': typeof DashboardSchedulesRouteWithChildren
  '/dashboard/templates': typeof DashboardTemplatesRouteWithChildren
  '/dashboard/tours': typeof DashboardToursRouteWithChildren
  '/dashboard/vacations': typeof DashboardVacationsRouteWithChildren
  '/dashboard/vehicles': typeof DashboardVehiclesRouteWithChildren
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/assignments/$assignmentId': typeof DashboardAssignmentsAssignmentIdRoute
  '/dashboard/assignments/new': typeof DashboardAssignmentsNewRoute
  '/dashboard/bookings/$bookingId': typeof DashboardBookingsBookingIdRouteWithChildren
  '/dashboard/bookings/new': typeof DashboardBookingsNewRoute
  '/dashboard/customers/$customerId': typeof DashboardCustomersCustomerIdRouteWithChildren
  '/dashboard/customers/new': typeof DashboardCustomersNewRoute
  '/dashboard/drivers/$driverId': typeof DashboardDriversDriverIdRoute
  '/dashboard/drivers/new': typeof DashboardDriversNewRoute
  '/dashboard/notifications/$templateId': typeof DashboardNotificationsTemplateIdRoute
  '/dashboard/notifications/new': typeof DashboardNotificationsNewRoute
  '/dashboard/notifications/settings': typeof DashboardNotificationsSettingsRoute
  '/dashboard/schedules/$scheduleId': typeof DashboardSchedulesScheduleIdRoute
  '/dashboard/schedules/new': typeof DashboardSchedulesNewRoute
  '/dashboard/settings/payments': typeof DashboardSettingsPaymentsRoute
  '/dashboard/templates/$templateId': typeof DashboardTemplatesTemplateIdRoute
  '/dashboard/templates/new': typeof DashboardTemplatesNewRoute
  '/dashboard/tours/$tourId': typeof DashboardToursTourIdRouteWithChildren
  '/dashboard/tours/new': typeof DashboardToursNewRoute
  '/dashboard/vacations/$vacationId': typeof DashboardVacationsVacationIdRoute
  '/dashboard/vacations/new': typeof DashboardVacationsNewRoute
  '/dashboard/vehicles/$vehicleId': typeof DashboardVehiclesVehicleIdRoute
  '/dashboard/vehicles/new': typeof DashboardVehiclesNewRoute
  '/dashboard/bookings/$bookingId/edit': typeof DashboardBookingsBookingIdEditRoute
  '/dashboard/customers/$customerId/edit': typeof DashboardCustomersCustomerIdEditRoute
  '/dashboard/tours/$tourId/edit': typeof DashboardToursTourIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/book/$slug': typeof BookSlugRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/assignments': typeof DashboardAssignmentsRouteWithChildren
  '/dashboard/bookings': typeof DashboardBookingsRouteWithChildren
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/customers': typeof DashboardCustomersRouteWithChildren
  '/dashboard/drivers': typeof DashboardDriversRouteWithChildren
  '/dashboard/notifications': typeof DashboardNotificationsRouteWithChildren
  '/dashboard/ota': typeof DashboardOtaRoute
  '/dashboard/schedules': typeof DashboardSchedulesRouteWithChildren
  '/dashboard/templates': typeof DashboardTemplatesRouteWithChildren
  '/dashboard/tours': typeof DashboardToursRouteWithChildren
  '/dashboard/vacations': typeof DashboardVacationsRouteWithChildren
  '/dashboard/vehicles': typeof DashboardVehiclesRouteWithChildren
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/assignments/$assignmentId': typeof DashboardAssignmentsAssignmentIdRoute
  '/dashboard/assignments/new': typeof DashboardAssignmentsNewRoute
  '/dashboard/bookings/$bookingId': typeof DashboardBookingsBookingIdRouteWithChildren
  '/dashboard/bookings/new': typeof DashboardBookingsNewRoute
  '/dashboard/customers/$customerId': typeof DashboardCustomersCustomerIdRouteWithChildren
  '/dashboard/customers/new': typeof DashboardCustomersNewRoute
  '/dashboard/drivers/$driverId': typeof DashboardDriversDriverIdRoute
  '/dashboard/drivers/new': typeof DashboardDriversNewRoute
  '/dashboard/notifications/$templateId': typeof DashboardNotificationsTemplateIdRoute
  '/dashboard/notifications/new': typeof DashboardNotificationsNewRoute
  '/dashboard/notifications/settings': typeof DashboardNotificationsSettingsRoute
  '/dashboard/schedules/$scheduleId': typeof DashboardSchedulesScheduleIdRoute
  '/dashboard/schedules/new': typeof DashboardSchedulesNewRoute
  '/dashboard/settings/payments': typeof DashboardSettingsPaymentsRoute
  '/dashboard/templates/$templateId': typeof DashboardTemplatesTemplateIdRoute
  '/dashboard/templates/new': typeof DashboardTemplatesNewRoute
  '/dashboard/tours/$tourId': typeof DashboardToursTourIdRouteWithChildren
  '/dashboard/tours/new': typeof DashboardToursNewRoute
  '/dashboard/vacations/$vacationId': typeof DashboardVacationsVacationIdRoute
  '/dashboard/vacations/new': typeof DashboardVacationsNewRoute
  '/dashboard/vehicles/$vehicleId': typeof DashboardVehiclesVehicleIdRoute
  '/dashboard/vehicles/new': typeof DashboardVehiclesNewRoute
  '/dashboard/bookings/$bookingId/edit': typeof DashboardBookingsBookingIdEditRoute
  '/dashboard/customers/$customerId/edit': typeof DashboardCustomersCustomerIdEditRoute
  '/dashboard/tours/$tourId/edit': typeof DashboardToursTourIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/book/$slug'
    | '/dashboard/analytics'
    | '/dashboard/assignments'
    | '/dashboard/bookings'
    | '/dashboard/categories'
    | '/dashboard/customers'
    | '/dashboard/drivers'
    | '/dashboard/notifications'
    | '/dashboard/ota'
    | '/dashboard/schedules'
    | '/dashboard/templates'
    | '/dashboard/tours'
    | '/dashboard/vacations'
    | '/dashboard/vehicles'
    | '/invite/$invitationId'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/assignments/$assignmentId'
    | '/dashboard/assignments/new'
    | '/dashboard/bookings/$bookingId'
    | '/dashboard/bookings/new'
    | '/dashboard/customers/$customerId'
    | '/dashboard/customers/new'
    | '/dashboard/drivers/$driverId'
    | '/dashboard/drivers/new'
    | '/dashboard/notifications/$templateId'
    | '/dashboard/notifications/new'
    | '/dashboard/notifications/settings'
    | '/dashboard/schedules/$scheduleId'
    | '/dashboard/schedules/new'
    | '/dashboard/settings/payments'
    | '/dashboard/templates/$templateId'
    | '/dashboard/templates/new'
    | '/dashboard/tours/$tourId'
    | '/dashboard/tours/new'
    | '/dashboard/vacations/$vacationId'
    | '/dashboard/vacations/new'
    | '/dashboard/vehicles/$vehicleId'
    | '/dashboard/vehicles/new'
    | '/dashboard/bookings/$bookingId/edit'
    | '/dashboard/customers/$customerId/edit'
    | '/dashboard/tours/$tourId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/book/$slug'
    | '/dashboard/analytics'
    | '/dashboard/assignments'
    | '/dashboard/bookings'
    | '/dashboard/categories'
    | '/dashboard/customers'
    | '/dashboard/drivers'
    | '/dashboard/notifications'
    | '/dashboard/ota'
    | '/dashboard/schedules'
    | '/dashboard/templates'
    | '/dashboard/tours'
    | '/dashboard/vacations'
    | '/dashboard/vehicles'
    | '/invite/$invitationId'
    | '/dashboard'
    | '/api/auth/$'
    | '/dashboard/assignments/$assignmentId'
    | '/dashboard/assignments/new'
    | '/dashboard/bookings/$bookingId'
    | '/dashboard/bookings/new'
    | '/dashboard/customers/$customerId'
    | '/dashboard/customers/new'
    | '/dashboard/drivers/$driverId'
    | '/dashboard/drivers/new'
    | '/dashboard/notifications/$templateId'
    | '/dashboard/notifications/new'
    | '/dashboard/notifications/settings'
    | '/dashboard/schedules/$scheduleId'
    | '/dashboard/schedules/new'
    | '/dashboard/settings/payments'
    | '/dashboard/templates/$templateId'
    | '/dashboard/templates/new'
    | '/dashboard/tours/$tourId'
    | '/dashboard/tours/new'
    | '/dashboard/vacations/$vacationId'
    | '/dashboard/vacations/new'
    | '/dashboard/vehicles/$vehicleId'
    | '/dashboard/vehicles/new'
    | '/dashboard/bookings/$bookingId/edit'
    | '/dashboard/customers/$customerId/edit'
    | '/dashboard/tours/$tourId/edit'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/book/$slug'
    | '/dashboard/analytics'
    | '/dashboard/assignments'
    | '/dashboard/bookings'
    | '/dashboard/categories'
    | '/dashboard/customers'
    | '/dashboard/drivers'
    | '/dashboard/notifications'
    | '/dashboard/ota'
    | '/dashboard/schedules'
    | '/dashboard/templates'
    | '/dashboard/tours'
    | '/dashboard/vacations'
    | '/dashboard/vehicles'
    | '/invite/$invitationId'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/assignments/$assignmentId'
    | '/dashboard/assignments/new'
    | '/dashboard/bookings/$bookingId'
    | '/dashboard/bookings/new'
    | '/dashboard/customers/$customerId'
    | '/dashboard/customers/new'
    | '/dashboard/drivers/$driverId'
    | '/dashboard/drivers/new'
    | '/dashboard/notifications/$templateId'
    | '/dashboard/notifications/new'
    | '/dashboard/notifications/settings'
    | '/dashboard/schedules/$scheduleId'
    | '/dashboard/schedules/new'
    | '/dashboard/settings/payments'
    | '/dashboard/templates/$templateId'
    | '/dashboard/templates/new'
    | '/dashboard/tours/$tourId'
    | '/dashboard/tours/new'
    | '/dashboard/vacations/$vacationId'
    | '/dashboard/vacations/new'
    | '/dashboard/vehicles/$vehicleId'
    | '/dashboard/vehicles/new'
    | '/dashboard/bookings/$bookingId/edit'
    | '/dashboard/customers/$customerId/edit'
    | '/dashboard/tours/$tourId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  BookSlugRoute: typeof BookSlugRoute
  InviteInvitationIdRoute: typeof InviteInvitationIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/invite/$invitationId': {
      id: '/invite/$invitationId'
      path: '/invite/$invitationId'
      fullPath: '/invite/$invitationId'
      preLoaderRoute: typeof InviteInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/vehicles': {
      id: '/dashboard/vehicles'
      path: '/vehicles'
      fullPath: '/dashboard/vehicles'
      preLoaderRoute: typeof DashboardVehiclesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/vacations': {
      id: '/dashboard/vacations'
      path: '/vacations'
      fullPath: '/dashboard/vacations'
      preLoaderRoute: typeof DashboardVacationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tours': {
      id: '/dashboard/tours'
      path: '/tours'
      fullPath: '/dashboard/tours'
      preLoaderRoute: typeof DashboardToursRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/templates': {
      id: '/dashboard/templates'
      path: '/templates'
      fullPath: '/dashboard/templates'
      preLoaderRoute: typeof DashboardTemplatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/schedules': {
      id: '/dashboard/schedules'
      path: '/schedules'
      fullPath: '/dashboard/schedules'
      preLoaderRoute: typeof DashboardSchedulesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ota': {
      id: '/dashboard/ota'
      path: '/ota'
      fullPath: '/dashboard/ota'
      preLoaderRoute: typeof DashboardOtaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/drivers': {
      id: '/dashboard/drivers'
      path: '/drivers'
      fullPath: '/dashboard/drivers'
      preLoaderRoute: typeof DashboardDriversRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/customers': {
      id: '/dashboard/customers'
      path: '/customers'
      fullPath: '/dashboard/customers'
      preLoaderRoute: typeof DashboardCustomersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/categories': {
      id: '/dashboard/categories'
      path: '/categories'
      fullPath: '/dashboard/categories'
      preLoaderRoute: typeof DashboardCategoriesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bookings': {
      id: '/dashboard/bookings'
      path: '/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof DashboardBookingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/assignments': {
      id: '/dashboard/assignments'
      path: '/assignments'
      fullPath: '/dashboard/assignments'
      preLoaderRoute: typeof DashboardAssignmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/book/$slug': {
      id: '/book/$slug'
      path: '/book/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/vehicles/new': {
      id: '/dashboard/vehicles/new'
      path: '/new'
      fullPath: '/dashboard/vehicles/new'
      preLoaderRoute: typeof DashboardVehiclesNewRouteImport
      parentRoute: typeof DashboardVehiclesRoute
    }
    '/dashboard/vehicles/$vehicleId': {
      id: '/dashboard/vehicles/$vehicleId'
      path: '/$vehicleId'
      fullPath: '/dashboard/vehicles/$vehicleId'
      preLoaderRoute: typeof DashboardVehiclesVehicleIdRouteImport
      parentRoute: typeof DashboardVehiclesRoute
    }
    '/dashboard/vacations/new': {
      id: '/dashboard/vacations/new'
      path: '/new'
      fullPath: '/dashboard/vacations/new'
      preLoaderRoute: typeof DashboardVacationsNewRouteImport
      parentRoute: typeof DashboardVacationsRoute
    }
    '/dashboard/vacations/$vacationId': {
      id: '/dashboard/vacations/$vacationId'
      path: '/$vacationId'
      fullPath: '/dashboard/vacations/$vacationId'
      preLoaderRoute: typeof DashboardVacationsVacationIdRouteImport
      parentRoute: typeof DashboardVacationsRoute
    }
    '/dashboard/tours/new': {
      id: '/dashboard/tours/new'
      path: '/new'
      fullPath: '/dashboard/tours/new'
      preLoaderRoute: typeof DashboardToursNewRouteImport
      parentRoute: typeof DashboardToursRoute
    }
    '/dashboard/tours/$tourId': {
      id: '/dashboard/tours/$tourId'
      path: '/$tourId'
      fullPath: '/dashboard/tours/$tourId'
      preLoaderRoute: typeof DashboardToursTourIdRouteImport
      parentRoute: typeof DashboardToursRoute
    }
    '/dashboard/templates/new': {
      id: '/dashboard/templates/new'
      path: '/new'
      fullPath: '/dashboard/templates/new'
      preLoaderRoute: typeof DashboardTemplatesNewRouteImport
      parentRoute: typeof DashboardTemplatesRoute
    }
    '/dashboard/templates/$templateId': {
      id: '/dashboard/templates/$templateId'
      path: '/$templateId'
      fullPath: '/dashboard/templates/$templateId'
      preLoaderRoute: typeof DashboardTemplatesTemplateIdRouteImport
      parentRoute: typeof DashboardTemplatesRoute
    }
    '/dashboard/settings/payments': {
      id: '/dashboard/settings/payments'
      path: '/settings/payments'
      fullPath: '/dashboard/settings/payments'
      preLoaderRoute: typeof DashboardSettingsPaymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/schedules/new': {
      id: '/dashboard/schedules/new'
      path: '/new'
      fullPath: '/dashboard/schedules/new'
      preLoaderRoute: typeof DashboardSchedulesNewRouteImport
      parentRoute: typeof DashboardSchedulesRoute
    }
    '/dashboard/schedules/$scheduleId': {
      id: '/dashboard/schedules/$scheduleId'
      path: '/$scheduleId'
      fullPath: '/dashboard/schedules/$scheduleId'
      preLoaderRoute: typeof DashboardSchedulesScheduleIdRouteImport
      parentRoute: typeof DashboardSchedulesRoute
    }
    '/dashboard/notifications/settings': {
      id: '/dashboard/notifications/settings'
      path: '/settings'
      fullPath: '/dashboard/notifications/settings'
      preLoaderRoute: typeof DashboardNotificationsSettingsRouteImport
      parentRoute: typeof DashboardNotificationsRoute
    }
    '/dashboard/notifications/new': {
      id: '/dashboard/notifications/new'
      path: '/new'
      fullPath: '/dashboard/notifications/new'
      preLoaderRoute: typeof DashboardNotificationsNewRouteImport
      parentRoute: typeof DashboardNotificationsRoute
    }
    '/dashboard/notifications/$templateId': {
      id: '/dashboard/notifications/$templateId'
      path: '/$templateId'
      fullPath: '/dashboard/notifications/$templateId'
      preLoaderRoute: typeof DashboardNotificationsTemplateIdRouteImport
      parentRoute: typeof DashboardNotificationsRoute
    }
    '/dashboard/drivers/new': {
      id: '/dashboard/drivers/new'
      path: '/new'
      fullPath: '/dashboard/drivers/new'
      preLoaderRoute: typeof DashboardDriversNewRouteImport
      parentRoute: typeof DashboardDriversRoute
    }
    '/dashboard/drivers/$driverId': {
      id: '/dashboard/drivers/$driverId'
      path: '/$driverId'
      fullPath: '/dashboard/drivers/$driverId'
      preLoaderRoute: typeof DashboardDriversDriverIdRouteImport
      parentRoute: typeof DashboardDriversRoute
    }
    '/dashboard/customers/new': {
      id: '/dashboard/customers/new'
      path: '/new'
      fullPath: '/dashboard/customers/new'
      preLoaderRoute: typeof DashboardCustomersNewRouteImport
      parentRoute: typeof DashboardCustomersRoute
    }
    '/dashboard/customers/$customerId': {
      id: '/dashboard/customers/$customerId'
      path: '/$customerId'
      fullPath: '/dashboard/customers/$customerId'
      preLoaderRoute: typeof DashboardCustomersCustomerIdRouteImport
      parentRoute: typeof DashboardCustomersRoute
    }
    '/dashboard/bookings/new': {
      id: '/dashboard/bookings/new'
      path: '/new'
      fullPath: '/dashboard/bookings/new'
      preLoaderRoute: typeof DashboardBookingsNewRouteImport
      parentRoute: typeof DashboardBookingsRoute
    }
    '/dashboard/bookings/$bookingId': {
      id: '/dashboard/bookings/$bookingId'
      path: '/$bookingId'
      fullPath: '/dashboard/bookings/$bookingId'
      preLoaderRoute: typeof DashboardBookingsBookingIdRouteImport
      parentRoute: typeof DashboardBookingsRoute
    }
    '/dashboard/assignments/new': {
      id: '/dashboard/assignments/new'
      path: '/new'
      fullPath: '/dashboard/assignments/new'
      preLoaderRoute: typeof DashboardAssignmentsNewRouteImport
      parentRoute: typeof DashboardAssignmentsRoute
    }
    '/dashboard/assignments/$assignmentId': {
      id: '/dashboard/assignments/$assignmentId'
      path: '/$assignmentId'
      fullPath: '/dashboard/assignments/$assignmentId'
      preLoaderRoute: typeof DashboardAssignmentsAssignmentIdRouteImport
      parentRoute: typeof DashboardAssignmentsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/tours/$tourId/edit': {
      id: '/dashboard/tours/$tourId/edit'
      path: '/edit'
      fullPath: '/dashboard/tours/$tourId/edit'
      preLoaderRoute: typeof DashboardToursTourIdEditRouteImport
      parentRoute: typeof DashboardToursTourIdRoute
    }
    '/dashboard/customers/$customerId/edit': {
      id: '/dashboard/customers/$customerId/edit'
      path: '/edit'
      fullPath: '/dashboard/customers/$customerId/edit'
      preLoaderRoute: typeof DashboardCustomersCustomerIdEditRouteImport
      parentRoute: typeof DashboardCustomersCustomerIdRoute
    }
    '/dashboard/bookings/$bookingId/edit': {
      id: '/dashboard/bookings/$bookingId/edit'
      path: '/edit'
      fullPath: '/dashboard/bookings/$bookingId/edit'
      preLoaderRoute: typeof DashboardBookingsBookingIdEditRouteImport
      parentRoute: typeof DashboardBookingsBookingIdRoute
    }
  }
}

interface DashboardAssignmentsRouteChildren {
  DashboardAssignmentsAssignmentIdRoute: typeof DashboardAssignmentsAssignmentIdRoute
  DashboardAssignmentsNewRoute: typeof DashboardAssignmentsNewRoute
}

const DashboardAssignmentsRouteChildren: DashboardAssignmentsRouteChildren = {
  DashboardAssignmentsAssignmentIdRoute: DashboardAssignmentsAssignmentIdRoute,
  DashboardAssignmentsNewRoute: DashboardAssignmentsNewRoute,
}

const DashboardAssignmentsRouteWithChildren =
  DashboardAssignmentsRoute._addFileChildren(DashboardAssignmentsRouteChildren)

interface DashboardBookingsBookingIdRouteChildren {
  DashboardBookingsBookingIdEditRoute: typeof DashboardBookingsBookingIdEditRoute
}

const DashboardBookingsBookingIdRouteChildren: DashboardBookingsBookingIdRouteChildren =
  {
    DashboardBookingsBookingIdEditRoute: DashboardBookingsBookingIdEditRoute,
  }

const DashboardBookingsBookingIdRouteWithChildren =
  DashboardBookingsBookingIdRoute._addFileChildren(
    DashboardBookingsBookingIdRouteChildren,
  )

interface DashboardBookingsRouteChildren {
  DashboardBookingsBookingIdRoute: typeof DashboardBookingsBookingIdRouteWithChildren
  DashboardBookingsNewRoute: typeof DashboardBookingsNewRoute
}

const DashboardBookingsRouteChildren: DashboardBookingsRouteChildren = {
  DashboardBookingsBookingIdRoute: DashboardBookingsBookingIdRouteWithChildren,
  DashboardBookingsNewRoute: DashboardBookingsNewRoute,
}

const DashboardBookingsRouteWithChildren =
  DashboardBookingsRoute._addFileChildren(DashboardBookingsRouteChildren)

interface DashboardCustomersCustomerIdRouteChildren {
  DashboardCustomersCustomerIdEditRoute: typeof DashboardCustomersCustomerIdEditRoute
}

const DashboardCustomersCustomerIdRouteChildren: DashboardCustomersCustomerIdRouteChildren =
  {
    DashboardCustomersCustomerIdEditRoute:
      DashboardCustomersCustomerIdEditRoute,
  }

const DashboardCustomersCustomerIdRouteWithChildren =
  DashboardCustomersCustomerIdRoute._addFileChildren(
    DashboardCustomersCustomerIdRouteChildren,
  )

interface DashboardCustomersRouteChildren {
  DashboardCustomersCustomerIdRoute: typeof DashboardCustomersCustomerIdRouteWithChildren
  DashboardCustomersNewRoute: typeof DashboardCustomersNewRoute
}

const DashboardCustomersRouteChildren: DashboardCustomersRouteChildren = {
  DashboardCustomersCustomerIdRoute:
    DashboardCustomersCustomerIdRouteWithChildren,
  DashboardCustomersNewRoute: DashboardCustomersNewRoute,
}

const DashboardCustomersRouteWithChildren =
  DashboardCustomersRoute._addFileChildren(DashboardCustomersRouteChildren)

interface DashboardDriversRouteChildren {
  DashboardDriversDriverIdRoute: typeof DashboardDriversDriverIdRoute
  DashboardDriversNewRoute: typeof DashboardDriversNewRoute
}

const DashboardDriversRouteChildren: DashboardDriversRouteChildren = {
  DashboardDriversDriverIdRoute: DashboardDriversDriverIdRoute,
  DashboardDriversNewRoute: DashboardDriversNewRoute,
}

const DashboardDriversRouteWithChildren =
  DashboardDriversRoute._addFileChildren(DashboardDriversRouteChildren)

interface DashboardNotificationsRouteChildren {
  DashboardNotificationsTemplateIdRoute: typeof DashboardNotificationsTemplateIdRoute
  DashboardNotificationsNewRoute: typeof DashboardNotificationsNewRoute
  DashboardNotificationsSettingsRoute: typeof DashboardNotificationsSettingsRoute
}

const DashboardNotificationsRouteChildren: DashboardNotificationsRouteChildren =
  {
    DashboardNotificationsTemplateIdRoute:
      DashboardNotificationsTemplateIdRoute,
    DashboardNotificationsNewRoute: DashboardNotificationsNewRoute,
    DashboardNotificationsSettingsRoute: DashboardNotificationsSettingsRoute,
  }

const DashboardNotificationsRouteWithChildren =
  DashboardNotificationsRoute._addFileChildren(
    DashboardNotificationsRouteChildren,
  )

interface DashboardSchedulesRouteChildren {
  DashboardSchedulesScheduleIdRoute: typeof DashboardSchedulesScheduleIdRoute
  DashboardSchedulesNewRoute: typeof DashboardSchedulesNewRoute
}

const DashboardSchedulesRouteChildren: DashboardSchedulesRouteChildren = {
  DashboardSchedulesScheduleIdRoute: DashboardSchedulesScheduleIdRoute,
  DashboardSchedulesNewRoute: DashboardSchedulesNewRoute,
}

const DashboardSchedulesRouteWithChildren =
  DashboardSchedulesRoute._addFileChildren(DashboardSchedulesRouteChildren)

interface DashboardTemplatesRouteChildren {
  DashboardTemplatesTemplateIdRoute: typeof DashboardTemplatesTemplateIdRoute
  DashboardTemplatesNewRoute: typeof DashboardTemplatesNewRoute
}

const DashboardTemplatesRouteChildren: DashboardTemplatesRouteChildren = {
  DashboardTemplatesTemplateIdRoute: DashboardTemplatesTemplateIdRoute,
  DashboardTemplatesNewRoute: DashboardTemplatesNewRoute,
}

const DashboardTemplatesRouteWithChildren =
  DashboardTemplatesRoute._addFileChildren(DashboardTemplatesRouteChildren)

interface DashboardToursTourIdRouteChildren {
  DashboardToursTourIdEditRoute: typeof DashboardToursTourIdEditRoute
}

const DashboardToursTourIdRouteChildren: DashboardToursTourIdRouteChildren = {
  DashboardToursTourIdEditRoute: DashboardToursTourIdEditRoute,
}

const DashboardToursTourIdRouteWithChildren =
  DashboardToursTourIdRoute._addFileChildren(DashboardToursTourIdRouteChildren)

interface DashboardToursRouteChildren {
  DashboardToursTourIdRoute: typeof DashboardToursTourIdRouteWithChildren
  DashboardToursNewRoute: typeof DashboardToursNewRoute
}

const DashboardToursRouteChildren: DashboardToursRouteChildren = {
  DashboardToursTourIdRoute: DashboardToursTourIdRouteWithChildren,
  DashboardToursNewRoute: DashboardToursNewRoute,
}

const DashboardToursRouteWithChildren = DashboardToursRoute._addFileChildren(
  DashboardToursRouteChildren,
)

interface DashboardVacationsRouteChildren {
  DashboardVacationsVacationIdRoute: typeof DashboardVacationsVacationIdRoute
  DashboardVacationsNewRoute: typeof DashboardVacationsNewRoute
}

const DashboardVacationsRouteChildren: DashboardVacationsRouteChildren = {
  DashboardVacationsVacationIdRoute: DashboardVacationsVacationIdRoute,
  DashboardVacationsNewRoute: DashboardVacationsNewRoute,
}

const DashboardVacationsRouteWithChildren =
  DashboardVacationsRoute._addFileChildren(DashboardVacationsRouteChildren)

interface DashboardVehiclesRouteChildren {
  DashboardVehiclesVehicleIdRoute: typeof DashboardVehiclesVehicleIdRoute
  DashboardVehiclesNewRoute: typeof DashboardVehiclesNewRoute
}

const DashboardVehiclesRouteChildren: DashboardVehiclesRouteChildren = {
  DashboardVehiclesVehicleIdRoute: DashboardVehiclesVehicleIdRoute,
  DashboardVehiclesNewRoute: DashboardVehiclesNewRoute,
}

const DashboardVehiclesRouteWithChildren =
  DashboardVehiclesRoute._addFileChildren(DashboardVehiclesRouteChildren)

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardAssignmentsRoute: typeof DashboardAssignmentsRouteWithChildren
  DashboardBookingsRoute: typeof DashboardBookingsRouteWithChildren
  DashboardCategoriesRoute: typeof DashboardCategoriesRoute
  DashboardCustomersRoute: typeof DashboardCustomersRouteWithChildren
  DashboardDriversRoute: typeof DashboardDriversRouteWithChildren
  DashboardNotificationsRoute: typeof DashboardNotificationsRouteWithChildren
  DashboardOtaRoute: typeof DashboardOtaRoute
  DashboardSchedulesRoute: typeof DashboardSchedulesRouteWithChildren
  DashboardTemplatesRoute: typeof DashboardTemplatesRouteWithChildren
  DashboardToursRoute: typeof DashboardToursRouteWithChildren
  DashboardVacationsRoute: typeof DashboardVacationsRouteWithChildren
  DashboardVehiclesRoute: typeof DashboardVehiclesRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardSettingsPaymentsRoute: typeof DashboardSettingsPaymentsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardAssignmentsRoute: DashboardAssignmentsRouteWithChildren,
  DashboardBookingsRoute: DashboardBookingsRouteWithChildren,
  DashboardCategoriesRoute: DashboardCategoriesRoute,
  DashboardCustomersRoute: DashboardCustomersRouteWithChildren,
  DashboardDriversRoute: DashboardDriversRouteWithChildren,
  DashboardNotificationsRoute: DashboardNotificationsRouteWithChildren,
  DashboardOtaRoute: DashboardOtaRoute,
  DashboardSchedulesRoute: DashboardSchedulesRouteWithChildren,
  DashboardTemplatesRoute: DashboardTemplatesRouteWithChildren,
  DashboardToursRoute: DashboardToursRouteWithChildren,
  DashboardVacationsRoute: DashboardVacationsRouteWithChildren,
  DashboardVehiclesRoute: DashboardVehiclesRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardSettingsPaymentsRoute: DashboardSettingsPaymentsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  BookSlugRoute: BookSlugRoute,
  InviteInvitationIdRoute: InviteInvitationIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
